### PR TITLE
#71 Implement MVP Sidebar

### LINKED ISSUE #71: Data Graph - Sidebar
### Description

We want to show all the data types on the side for a user to select. 

### Acceptance Criteria

- [ ] First Box is ARGOS 
- [ ] Next display all the nodes that are stored in the db underneath 
- [ ] Each node when selected will expand to display all the data types that have that node as their node in
- [ ] Selecting it again collapses the data
- [ ] Each data type should be displayed with the datatype name in large text above the current value and unit beneath it in smaller text
- [ ] All Nodes and datatypes are accounted for 
- [ ] Query the data from the backend

### Proposed Solution

Look at the angular mui documentation for something that might do this otherwise look it up

### Mocks

epic #70 
Screenshot 2023-10-12 at 9 58 04 AM

Screenshot 2023-10-23 at 9 49 44 PM

### PR DESCRIPTION
**Pull request by Peyton-McKee**
## Changes
Added Sidebar Implementation
Has Animation for Expanding and collapsing elements
Added Theme + Typography Implementation
Added Barebones Loading and Error Pages
Edited Backend to return data types with nodes
Added an app context to host and distribute services
Created Graph page

## Screenshots
Screenshot 2023-11-07 at 9 37 07 AM
Screenshot 2023-11-07 at 9 37 14 AM

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `package-lock.json` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #71  (issue #)

### CODE REVIEW

**Comment by Peyton-McKee** [comment]
New Screens
Screenshot 2023-11-07 at 3 22 28 PM
Screenshot 2023-11-07 at 3 23 00 PM

**Comment by Peyton-McKee** [comment]
animations 

https://github.com/Northeastern-Electric-Racing/Argos/assets/113635669/b86dccbf-ac13-4335-a762-b92a05068f99

**Review by leoleader — DISMISSED** [review]
looked it over looks very nice, only minor thing is wouldn't the error page and loading page be under pages instead of where they currently are in components?

**Comment by Peyton-McKee** [comment]
They could be, but they’re more used as components than pages themselves

**Comment by Peyton-McKee** [comment]
https://github.com/Northeastern-Electric-Racing/Argos/assets/113635669/1aa93c1c-8504-4bef-988b-dce231d90fe8
updated design

**Pull request merged**
